// 右键
export const SET_CONTEXT_FEATURE = 'SET_CONTEXT_FEATURE'
// 地图
export const SET_MAP_LOAD_STATE = 'SET_MAP_LOAD_STATE'
// 地图查询
export const SET_PERIMETER_LOCATION = 'SET_PERIMETER_LOCATION'
export const SET_PERIMETER_LAYER = 'SET_PERIMETER_LAYER'
export const SET_CONTROL_LEGEND = 'SET_CONTROL_LEGEND'
export const SET_TOP_TOOL = 'SET_TOP_TOOL'
export const SET_TOOL_PANEL = 'SET_TOOL_PANEL'
export const SET_CONTROL_DRAW = 'SET_CONTROL_DRAW'
export const SET_CONTROL_DRAW_ORIGINAL = 'SET_CONTROL_DRAW_ORIGINAL'
export const AUTHORITY_MANAGEMENT = 'AUTHORITY_MANAGEMENT'
export const REFRESH_FLAG = 'REFRESH_FLAG'
// dialog
export const SET_DIALOG_RELIEVE_CONTENT = 'SET_DIALOG_RELIEVE_CONTENT'
export const VIDEO_DIALOG_VISIBLE = 'VIDEO_DIALOG_VISIBLE'

// 路径分析
const SET_PATHANALYSIS_ORIGINS = 'SET_PATHANALYSIS_ORIGINS'
const SET_PATHANALYSIS_DESTINATION = 'SET_PATHANALYSIS_DESTINATION'
const SET_PATHANALYSIS_PASS = 'SET_PATHANALYSIS_PASS'
const SET_PATHANALYSIS_AVOID = 'SET_PATHANALYSIS_AVOID'

// 气泡相关事件
const ACTION_POPOVER_DETAIL = 'ACTION_POPOVER_DETAIL'
const ACTION_POPOVER_CONTROL = 'ACTION_POPOVER_CONTROL'
const ACTION_POPOVER_RELIEF = 'ACTION_POPOVER_RELIEF'

// 收费站管制
const ACTION_ASSOCIATION_CONTROL = 'ACTION_ASSOCIATION_CONTROL'
const UPDATE_TOLLSTATIONS = 'UPDATE_TOLLSTATIONS'
// 道路管制
const UPDATE_ROADSTATIONS = 'UPDATE_ROADSTATIONS'
const UPDATE_ROADSTATIONS_FUNC = 'UPDATE_ROADSTATIONS_FUNC'
// 阈值管理
const RESULT_LIST = 'RESULT_LIST'
const YZGL_CLOSE = 'YZGL_CLOSE'

export {
  SET_PATHANALYSIS_ORIGINS,
  SET_PATHANALYSIS_DESTINATION,
  SET_PATHANALYSIS_PASS,
  SET_PATHANALYSIS_AVOID,
  ACTION_POPOVER_DETAIL,
  ACTION_POPOVER_CONTROL,
  ACTION_POPOVER_RELIEF,
  ACTION_ASSOCIATION_CONTROL,
  UPDATE_TOLLSTATIONS,
  UPDATE_ROADSTATIONS,
  UPDATE_ROADSTATIONS_FUNC,
  RESULT_LIST,
  YZGL_CLOSE
}

const REFRESH_LIST = 'REFRESH_LIST'
const REFRESH_NOTICELIST = 'REFRESH_NOTICELIST'
const REFRESH_CONTROL_LIST_FLAG = 'REFRESH_CONTROL_LIST_FLAG'
const REFRESH_MEASURES_LIST_FLAG = 'REFRESH_MEASURES_LIST_FLAG'
const COMMEND_RECEIVE_STATE = 'COMMEND_RECEIVE_STATE'
const SET_COMMAND_DETAIL_CONTENT = 'SET_COMMAND_DETAIL_CONTENT'
const SET_REFRESH_CONTROL_LEGEND = 'SET_REFRESH_CONTROL_LEGEND'
export {
  REFRESH_NOTICELIST,
  REFRESH_CONTROL_LIST_FLAG,
  REFRESH_MEASURES_LIST_FLAG,
  COMMEND_RECEIVE_STATE,
  SET_COMMAND_DETAIL_CONTENT,
  SET_REFRESH_CONTROL_LEGEND,
  REFRESH_LIST
}

const SHOW_PANEL_RIGHT = 'SHOW_PANEL_RIGHT'
const CONTROL_PANEL = 'CONTROL_PANEL'
const LAYER_CONTROL = 'LAYER_CONTROL'
const SET_REFRESH_TRAFFIC_LIST = 'SET_REFRESH_TRAFFIC_LIST'
export {
  CONTROL_PANEL,
  SHOW_PANEL_RIGHT,
  LAYER_CONTROL,
  SET_REFRESH_TRAFFIC_LIST
}

const SET_CURRENT_HEADER = 'SET_CURRENT_HEADER'
const SET_SCHEDULING_DATA = 'SET_SCHEDULING_DATA'
const SET_SCHEDUE_REFRESH = 'SET_SCHEDUE_REFRESH'
export {
  SET_CURRENT_HEADER,
  SET_SCHEDULING_DATA,
  SET_SCHEDUE_REFRESH
}

const SET_NOTICE_PANEL = 'SET_NOTICE_PANEL'
export {
  SET_NOTICE_PANEL
}

const REFRESH_ROLE_LIST = 'REFRESH_ROLE_LIST'
export {
  REFRESH_ROLE_LIST
}

const REFRESH_EMER_DEPT_TREE = 'REFRESH_EMER_DEPT_TREE'
export {
  REFRESH_EMER_DEPT_TREE
}

const REFRESH_WARN_LIST_FLAG = 'REFRESH_WARN_LIST_FLAG'
const CHECK_TREE_ITEM = 'CHECK_TREE_ITEM'
const REFRESH_TREE = 'REFRESH_TREE'
export {
  REFRESH_TREE,
  CHECK_TREE_ITEM,
  REFRESH_WARN_LIST_FLAG
}
// 标绘
export const PLOT_PANEL_TYPE = 'PLOT_PANEL_TYPE'
export const PLOT_PANEL_THEME_DATA = 'PLOT_PANEL_THEME_DATA'
export const PLOT_PANEL_SCHEME_DATA = 'PLOT_PANEL_SCHEME_DATA'
